### ISSUE TITLE
[Question] Gitup Git2 Pro

### ISSUE THREAD

**Issue by oiacrasec** [rgov/novatek-api#2]
Hello!
Do you know if Gitup Git2 Pro cameras works like APEMAN 4k?
I really liked your project

**Comment by oiacrasec** [comment]
It worked!
How can i help to improve the project? Im trying to create a 360 street view photo (like google) using cheap cameras.
How did you reverse the app CamKing?

**Comment by rgov** [comment]
I wrote a blog post about reverse engineering the app here: https://ryan.govost.es/2018/03/27/sakuracam.html

What do you want to improve?
